#!/usr/bin/env python3
paclog=[i.replace('[','').replace(']','').split() for i in open('/var/log/pacman.log')]
upgrade={}
for i in paclog:
    if i.count('upgraded')>0:
        if i[0] in upgrade.keys():
            upgrade[i[0]]+=1
        else:
            upgrade[i[0]]=1
        

for i in sorted(upgrade):
    print('\033[1;31;40m'+i+': \033[1;32;40m',end='')
    #print (': upgrade ',upgrade[i])
    print('upgrade: ',upgrade[i],end='')
    print('\033[0m')
